services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: argo_db
    environment:
      - POSTGRES_USER=argo
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=argodb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always